# Generated by Django 3.0.7 on 2020-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('key_term_injured', models.CharField(max_length=1000)),
                ('key_term_killed', models.CharField(max_length=1000)),
                ('accident_related', models.BooleanField(default=False)),
                ('informative', models.BooleanField(default=False)),
                ('num_killed', models.IntegerField(default=0)),
                ('num_vehicles', models.IntegerField(default=0)),
                ('key_term_num_vehicles', models.CharField(max_length=1000)),
                ('num_injured', models.IntegerField(default=0)),
                ('is_annotated', models.BooleanField(default=False)),
            ],
        ),
    ]
