# Generated by Django 3.0.7 on 2020-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='severity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='key_term_injured',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='key_term_killed',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='key_term_num_vehicles',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
